[2025-09-09T17:37:48.369+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: banvic_etl.extract_sql_db manual__2025-09-09T17:37:46.103611+00:00 [queued]>
[2025-09-09T17:37:48.382+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: banvic_etl.extract_sql_db manual__2025-09-09T17:37:46.103611+00:00 [queued]>
[2025-09-09T17:37:48.383+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-09-09T17:37:48.411+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): extract_sql_db> on 2025-09-09 17:37:46.103611+00:00
[2025-09-09T17:37:48.428+0000] {standard_task_runner.py:60} INFO - Started process 2386 to run task
[2025-09-09T17:37:48.436+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'banvic_etl', 'extract_sql_db', 'manual__2025-09-09T17:37:46.103611+00:00', '--job-id', '137', '--raw', '--subdir', 'DAGS_FOLDER/bavic_dag.py', '--cfg-path', '/tmp/tmpeptzc4cr']
[2025-09-09T17:37:48.440+0000] {standard_task_runner.py:88} INFO - Job 137: Subtask extract_sql_db
[2025-09-09T17:37:48.650+0000] {task_command.py:423} INFO - Running <TaskInstance: banvic_etl.extract_sql_db manual__2025-09-09T17:37:46.103611+00:00 [running]> on host 9948058d4968
[2025-09-09T17:37:48.946+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Paulo' AIRFLOW_CTX_DAG_ID='banvic_etl' AIRFLOW_CTX_TASK_ID='extract_sql_db' AIRFLOW_CTX_EXECUTION_DATE='2025-09-09T17:37:46.103611+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-09T17:37:46.103611+00:00'
[2025-09-09T17:37:49.060+0000] {logging_mixin.py:188} WARNING - /opt/airflow/scripts/extract_helpers.py:33 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-09-09T17:37:49.232+0000] {logging_mixin.py:188} WARNING - /opt/airflow/scripts/extract_helpers.py:33 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-09-09T17:37:49.291+0000] {logging_mixin.py:188} WARNING - /opt/airflow/scripts/extract_helpers.py:33 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-09-09T17:37:49.374+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-09-09T17:37:49.419+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=banvic_etl, task_id=extract_sql_db, execution_date=20250909T173746, start_date=20250909T173748, end_date=20250909T173749
[2025-09-09T17:37:49.500+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-09-09T17:37:49.570+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
