[2025-09-09T14:58:06.480+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: banvic_etl.extract_sql_db manual__2025-09-04T16:49:13.653051+00:00 [queued]>
[2025-09-09T14:58:06.506+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: banvic_etl.extract_sql_db manual__2025-09-04T16:49:13.653051+00:00 [queued]>
[2025-09-09T14:58:06.508+0000] {taskinstance.py:2170} INFO - Starting attempt 9 of 9
[2025-09-09T14:58:06.550+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): extract_sql_db> on 2025-09-04 16:49:13.653051+00:00
[2025-09-09T14:58:06.584+0000] {standard_task_runner.py:60} INFO - Started process 498 to run task
[2025-09-09T14:58:06.596+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'banvic_etl', 'extract_sql_db', 'manual__2025-09-04T16:49:13.653051+00:00', '--job-id', '126', '--raw', '--subdir', 'DAGS_FOLDER/bavic_dag.py', '--cfg-path', '/tmp/tmpbbnqg4fe']
[2025-09-09T14:58:06.610+0000] {standard_task_runner.py:88} INFO - Job 126: Subtask extract_sql_db
[2025-09-09T14:58:07.049+0000] {task_command.py:423} INFO - Running <TaskInstance: banvic_etl.extract_sql_db manual__2025-09-04T16:49:13.653051+00:00 [running]> on host 9948058d4968
[2025-09-09T14:58:07.763+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Paulo' AIRFLOW_CTX_DAG_ID='banvic_etl' AIRFLOW_CTX_TASK_ID='extract_sql_db' AIRFLOW_CTX_EXECUTION_DATE='2025-09-04T16:49:13.653051+00:00' AIRFLOW_CTX_TRY_NUMBER='9' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-04T16:49:13.653051+00:00'
[2025-09-09T14:58:07.937+0000] {logging_mixin.py:188} WARNING - /opt/airflow/scripts/extract_helpers.py:33 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-09-09T14:58:08.192+0000] {logging_mixin.py:188} WARNING - /opt/airflow/scripts/extract_helpers.py:33 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-09-09T14:58:08.319+0000] {logging_mixin.py:188} WARNING - /opt/airflow/scripts/extract_helpers.py:33 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-09-09T14:58:08.496+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-09-09T14:58:08.595+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=banvic_etl, task_id=extract_sql_db, execution_date=20250904T164913, start_date=20250909T145806, end_date=20250909T145808
[2025-09-09T14:58:08.789+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-09-09T14:58:08.940+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
