[2025-09-09T14:52:57.865+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: banvic_etl.extract_sql_db manual__2025-09-04T16:11:37.161994+00:00 [queued]>
[2025-09-09T14:52:57.931+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: banvic_etl.extract_sql_db manual__2025-09-04T16:11:37.161994+00:00 [queued]>
[2025-09-09T14:52:57.933+0000] {taskinstance.py:2170} INFO - Starting attempt 8 of 9
[2025-09-09T14:52:58.038+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): extract_sql_db> on 2025-09-04 16:11:37.161994+00:00
[2025-09-09T14:52:58.090+0000] {standard_task_runner.py:60} INFO - Started process 355 to run task
[2025-09-09T14:52:58.266+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'banvic_etl', 'extract_sql_db', 'manual__2025-09-04T16:11:37.161994+00:00', '--job-id', '91', '--raw', '--subdir', 'DAGS_FOLDER/bavic_dag.py', '--cfg-path', '/tmp/tmpj7elz9bc']
[2025-09-09T14:52:58.364+0000] {standard_task_runner.py:88} INFO - Job 91: Subtask extract_sql_db
[2025-09-09T14:53:00.219+0000] {task_command.py:423} INFO - Running <TaskInstance: banvic_etl.extract_sql_db manual__2025-09-04T16:11:37.161994+00:00 [running]> on host 9948058d4968
[2025-09-09T14:53:01.873+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Paulo' AIRFLOW_CTX_DAG_ID='banvic_etl' AIRFLOW_CTX_TASK_ID='extract_sql_db' AIRFLOW_CTX_EXECUTION_DATE='2025-09-04T16:11:37.161994+00:00' AIRFLOW_CTX_TRY_NUMBER='8' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-04T16:11:37.161994+00:00'
[2025-09-09T14:53:03.051+0000] {logging_mixin.py:188} WARNING - /opt/airflow/scripts/extract_helpers.py:33 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-09-09T14:53:03.796+0000] {logging_mixin.py:188} WARNING - /opt/airflow/scripts/extract_helpers.py:33 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-09-09T14:53:04.067+0000] {logging_mixin.py:188} WARNING - /opt/airflow/scripts/extract_helpers.py:33 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-09-09T14:53:04.426+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-09-09T14:53:04.716+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=banvic_etl, task_id=extract_sql_db, execution_date=20250904T161137, start_date=20250909T145257, end_date=20250909T145304
[2025-09-09T14:53:04.922+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-09-09T14:53:05.118+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
